/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../lib/session-store`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracion` | `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manguito` | `/manguito`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/nuevo` | `/nuevo`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../lib/session-store`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configuracion` | `/configuracion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/manguito` | `/manguito`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/nuevo` | `/nuevo`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../lib/session-store${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configuracion${`?${string}` | `#${string}` | ''}` | `/configuracion${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/manguito${`?${string}` | `#${string}` | ''}` | `/manguito${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/nuevo${`?${string}` | `#${string}` | ''}` | `/nuevo${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../lib/session-store`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracion` | `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manguito` | `/manguito`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/nuevo` | `/nuevo`; params?: Router.UnknownInputParams; };
    }
  }
}
